# runner image for building docker containers
# image name: pimages/github-actions-runner-docker

FROM pimages/github-actions-runner:latest

ARG PACKAGES="docker.io"

USER root

# install packages
RUN apt-get update \
    && apt-get install -y -q ${PACKAGES} \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# configure docker group
RUN groupmod -g 125 docker \
    && usermod -a -G docker runner

USER runner
